version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # pgAdmin 登錄的電子郵件
      PGADMIN_DEFAULT_PASSWORD: admin          # pgAdmin 登錄的密碼
    ports:
      - "8080:80" # 映射 pgAdmin 的端口
    volumes:
      - /workspace/gitpod-supertoken-demo/docker-data/pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - web
      
networks:
  web:
    external: true