version: '3'

services:
  # Note: If you are assigning a custom name to your db service on the line below, make sure it does not contain underscores
  supertokens-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: supertokens_user 
      POSTGRES_PASSWORD: somePassword 
      POSTGRES_DB: supertokens
    ports:
      - 7005:5432
    volumes:
      - /workspace/gitpod-supertoken-demo/docker-data/supertokens/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - web
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'supertokens_user', '-d', 'supertokens']
      interval: 5s
      timeout: 5s
      retries: 5

  
 
networks:
  web:
    external: true