version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest  # 使用 Portainer 社區版
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Portainer Web UI 預設為 9000 端口
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # 掛載 Docker Socket
      - "/workspace/gitpod-supertoken-demo/docker-data/portainer:/data"  # 持久化數據存儲
    environment:
      - TZ=Asia/Taipei  # 設置時區，根據你的地區修改
      - ADMIN_USERNAME=admin  # 管理員帳號
      - ADMIN_PASSWORD=1qaz2wsx3edc  # 管理員密碼
